# -*- coding: utf-8 -*-
"""projetos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a9-nZ00-6z6XHcbv5TCChrf9EfaY-60G

#Projeto 1:
  - Leitor de Arquivo CSV de contatos
"""

#importando o módulo csv
import csv

#Leitura de arquivos CSV
with open('contato.csv', 'r') as arquivo:
  leitor = csv.DictReader(arquivo)
  contatos=[]
  for linha in leitor:
    contatos.append(linha)

#teste
#print(contatos)

def buscar_contato(contatos, campo, termo):
  resultado = []
  for contato in contatos:
    valor = contato[campo]
    if termo.lower() in valor.lower():
      resultado.append(contato)
  return resultado


b = 's';

while b!='n' and b == 's':
  print("Digite a opção que deseja: ");
  print("1 - Para pesquisar por nome");
  print("2 - Para pesquisar por email")
  print("3 - Para pesquisar por telefone");

  a = int(input());

  if a ==1:
    nome = input("Digite o nome que deseja pesquisar: ");
    resultado = buscar_contato(contatos, 'nome', nome);
    print(resultado);
  elif a ==2:
    email = input("Digite o email que deseja pesquisar: ");
    resultado = buscar_contato(contatos, 'email', email);
    print(resultado);
  elif a ==3:
    telefone = input("Digite o telefone que deseja pesquisar: ");
    resultado = buscar_contato(contatos, 'telefone', telefone);
    print(resultado);
  else:
    print("Opção inválida");

  print("Deseja continuar? (s/n)");
  b = input();
print("Até mais!");